<template>
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">
                ODE file
            </h3>
            <i class="fa fa-info-circle pull-right"></i>
        </div>

        <div class="box-body">
            <textarea class="form-control"
                      style="height: 70.5vh"
                      @blur="notify"
                      v-model="ode">
            </textarea>
        </div>
    </div>
</template>

<script type="text/babel">
    export default {
        props: ['ics', 'des', 'params', 'options', 'ode'],

        ready() {
            this.ode = this.generate();
        },

        watch: {
            'ics': {
                deep: true,
                handler() { this.ode = this.generate() }
            },
            'des': {
                deep: true,
                handler() { this.ode = this.generate() }
            },
            'params': {
                deep: true,
                handler() { this.ode = this.generate() }
            },
            'options': {
                deep: true,
                handler() { this.ode = this.generate() }
            }
        },

        methods: {
            /**
             * Renders ODE file based on given data
             *
             * @returns {string}
             */
            generate() {
                const header = '# Generated by XppWeb\n# Created: ' + (new Date()) + '\n';
                const footer = '\n' + 'done';

                let data = {
                    ics: this.ics,
                    params: this.params,
                    des: this.des,
                    options: this.options
                };

                return header + Object.keys(data).reduce((prev, curr) => {
                    const type = this.formatType(curr);

                    return prev + '\n' + type.description + data[curr].reduce((previous, current) => {
                        return previous + this.formatField(current, type);
                    }, '');
                }, '') + footer;
            },

            /**
             * Format field from input box
             *
             * @param {object} field - Input box' field
             * @param {object} type - Formatted type of input box
             * @returns {string}
             */
            formatField(field, type) {
                if (field.key && field.value && field.value !== '' && field.value !== 'undefined') {
                    return `${type.prefix}${field.key} = ${field.value}\n`;
                }

                return '';
            },

            /**
             * Specify the prefix and description for given type
             *
             * @param type {string}
             * @returns {{prefix: string, description: string}}
             */
            formatType(type) {
                let prefix = '';
                let description = '';

                switch(type) {
                    case 'ics':
                        prefix = 'init ';
                        description = '# Initial conditions\n';
                        break;
                    case 'options':
                        prefix = '@ ';
                        description = '# Options\n';
                        break;
                    case 'des':
                        description = '# Differential equations\n';
                        break;
                    case 'params':
                        description = '# Parameters\n';
                        break;
                }

                return { prefix, description };
            },

            notify() {
                this.$parent.parse();
            }
        }
    }
</script>